# Generated by Django 3.1 on 2020-08-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'In Progress'), ('DONE', 'Done'), ('Invalid', 'Invalid')], default='NEW', max_length=80),
        ),
    ]
